USE FoodDelivery2;

CREATE TABLE [Role]
(
	ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
	CONSTRAINT PK_Role PRIMARY KEY
	, RoleName NVARCHAR(50) NOT NULL
);

ALTER TABLE [Role]
ADD CONSTRAINT u_RoleName UNIQUE(RoleName);

ALTER TABLE [Role]
ADD CONSTRAINT ch_RoleName
CHECK (LEN(RoleName) > 1);

SELECT *
FROM [Role];

--DROP TABLE [Role];