USE FoodDelivery2;

CREATE TABLE [Order]
(
	 ID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()
	  CONSTRAINT PK_Order PRIMARY KEY
	, ID_Customer UNIQUEIDENTIFIER NOT NULL
	  CONSTRAINT FK_Customer FOREIGN KEY 
	  REFERENCES Person(ID)
	  ON DELETE CASCADE 
	  ON UPDATE CASCADE
	, ID_Courier UNIQUEIDENTIFIER NOT NULL
	  CONSTRAINT FK_Courier FOREIGN KEY
	  REFERENCES Person(ID)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION,
	  [Address] VARCHAR(50) NOT NULL,
	  GetTime TIME NOT NULL,
	  DeliveryTime TIME NOT NULL
);

ALTER TABLE [Order]
ADD CONSTRAINT ch_Address
CHECK (LEN([Address]) > 1);

ALTER TABLE [Order]
ADD CONSTRAINT ch_GetTime
CHECK (LEN(GetTime) > 1);

ALTER TABLE [Order]
ADD CONSTRAINT ch_DeliveryTime
CHECK (LEN(DeliveryTime) > 1);

--DROP TABLE [Order];