CREATE FUNCTION dbo.fRoleID
(
	@RoleName NVARCHAR(50)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Role UNIQUEIDENTIFIER = 
			(SELECT TOP 1 ID
			FROM Role
			WHERE RoleName = @RoleName);
	RETURN @ID_Role
END;