USE FoodDelivery;

CREATE TABLE Person 
(
	PersonID INT PRIMARY KEY IDENTITY(1,1),
	FullName VARCHAR(255) NOT NULL,
	PhoneNumber VARCHAR(255) NOT NULL
);

CREATE TABLE [Role] 
(
	RoleID INT PRIMARY KEY IDENTITY(1,1),
	RoleName VARCHAR(255) NOT NULL
);

CREATE TABLE PersonRole 
(
	PersonRoleID INT PRIMARY KEY IDENTITY(1,1),
	PersonID INT NOT NULL,
	FOREIGN KEY (PersonID) REFERENCES Person (PersonID),
	RoleID INT NOT NULL,
	FOREIGN KEY (RoleID) REFERENCES Role (RoleID)
);

CREATE TABLE Product
(
	ProductID INT PRIMARY KEY IDENTITY(1,1),
	MenuName VARCHAR(255) NOT NULL,
	Price FLOAT NOT NULL
);

CREATE TABLE [Order]
(
	OrderID INT PRIMARY KEY IDENTITY(1,1),
	CustomerID INT NOT NULL,
	FOREIGN KEY (CustomerID) REFERENCES Person (PersonID),
	CourierID INT NOT NULL,
	FOREIGN KEY (CourierID) REFERENCES Person (PersonID),
	[Address] VARCHAR(255) NOT NULL,
	GetTime TIME NOT NULL,
	DeliveryTime TIME NOT NULL
);

CREATE TABLE OrderProduct
(
	OrderProductID INT PRIMARY KEY IDENTITY(1,1),
	OrderID INT NOT NULL,
	FOREIGN KEY (OrderID) REFERENCES [Order] (OrderID),
	ProductID INT NOT NULL,
	FOREIGN KEY (ProductID) REFERENCES Product (ProductID)
);